version: "3.8"

services:
  receiver-db:
    image: postgres:latest
    container_name: receiver-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=receiver-db
    ports:
      - "5434:5432"

  farmNear:
    image: mongo:latest
    container_name: farmNear
    ports:
      - "27017:27017"

  patient-db:
    image: postgres:latest
    container_name: patient-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=patient-db
    ports:
      - "5433:5432"

  finder-db:
    image: postgres:latest
    container_name: finder-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finder-db
    ports:
      - "5435:5432"

  receiver:
    image: julioborges05/farmanear-receiver
    container_name: farmanear-receiver
    environment:
      - DB_URL=${DB_URL_RECEIVER}
      - DB_USER=${DB_USER_RECEIVER}
      - DB_PASSWORD=${DB_PASSWORD_RECEIVER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_TIMEOUT_MINUTES=${JWT_SECRET_TIMEOUT_MINUTES}
      - FRONT_URL={FRONT_URL}
      - PHARMACY_SERVICE_URL=${PHARMACY_SERVICE_URL}
      - PATIENT_SERVICE_URL=${PATIENT_SERVICE_URL}
      - FINDER_SERVICE_URL=${FINDER_SERVICE_URL}
    ports:
      - "8080:8080"

  pharmacy:
    image: julioborges05/farmanear-register
    container_name: farmanear-register
    environment:
      - DB_URL=${DB_URL_PHARMACY}
      - JWT_SECRET=${JWT_SECRET}
      - FRONT_URL={FRONT_URL}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  finder:
    image: julioborges05/farmanear-finder
    container_name: farmanear-finder
    environment:
      - DB_URL=${DB_URL_FINDER}
      - DB_USER=${DB_USER_FINDER}
      - DB_PASSWORD=${DB_PASSWORD_FINDER}
      - PHARMACY_SERVICE_URL=${PHARMACY_SERVICE_URL}
      - PATIENT_SERVICE_URL=${PATIENT_SERVICE_URL}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'