FROM amazoncorretto:21.0.4-alpine3.18

WORKDIR /app

ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_SECRET_TIMEOUT_MINUTES=${JWT_SECRET_TIMEOUT_MINUTES}
ENV FRONT_URL=${FRONT_URL}
ENV PHARMACY_SERVICE_URL=${PHARMACY_SERVICE_URL}
ENV PATIENT_SERVICE_URL=${PATIENT_SERVICE_URL}
ENV FINDER_SERVICE_URL=${FINDER_SERVICE_URL}

COPY target/FarmaNear-Receiver-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]